variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  HTTP_PROXY: http://fifi:8080/
  HTTPS_PROXY: http://fifi:8080/
  NO_PROXY: "docker:2375,docker:2376"
 
stages:
  - test
  - build
  - deploy
image:
  name: python:3.6

before_script:
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry config pypi-token.pypi ${PYPI_TOKEN}
  - poetry lock
  - poetry install

build:
  only:
      refs:
        - pipelines
        - triggers
        - master

  stage: build
  tags:
    - cluster
  script:
    - poetry run bash checkandbump.sh
    - poetry publish --build

trigger_build:
  only:
     refs:
         - master
  stage: deploy
  trigger: acdh-oeaw/apis/apis-docker
  variables:
      APIS_TRIGGERD_BY: 'apis-core'
      APIS_VERSION: '0.9'
