# Generated by Django 2.1.12 on 2020-01-21 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bibs_url', models.URLField()),
                ('pages_start', models.PositiveIntegerField(blank=True, null=True)),
                ('pages_end', models.PositiveIntegerField(blank=True, null=True)),
                ('bibtex', models.TextField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('attribute', models.CharField(blank=True, max_length=255, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
