# Generated by Django 5.1.1 on 2024-09-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_bibsonomy", "0003_auto_20230202_0953"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reference",
            name="bibtex",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
