# Generated by Django 5.2.6 on 2026-03-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_bibsonomy", "0004_alter_reference_bibtex"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZoteroEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("version", models.IntegerField(null=True)),
                ("data", models.JSONField(null=True)),
            ],
        ),
    ]
