# Generated by Django 5.2.5 on 2026-09-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_bibsonomy", "0005_zoteroentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zoteroentry",
            name="url",
            field=models.URLField(unique=True),
        ),
    ]
